### ISSUE TITLE
Bunnycdn to storage.bunnycdn.com responds with 401 - please change to ny.storage.bunnycdn.com

### ISSUE THREAD

**Issue by deepanprabhu** [BunnyWay/BunnyCDN.Java.Storage#10]
https://twitter.com/ItsCryptkeeper/status/1289643205818855424

**Comment by doghouch** [comment]
Hello,

It is written in the Java documentation:

> By default, when no location is specified, this module assumes that your zone is part of the de region (if your zone isn't replicated or you've enabled the replication feature on an old storage zone -> there is no need to specify a location).

I’m not sure what you/the person tweeting is referring to. It might be another module (in which case, the issue should be opened there).


Aaron

**Comment by deepanprabhu** [comment]
Thanks @doghouch , that was helpful.

- Would recommend to have an ENUM with different regions which BunnyCDN supports,
- As a user, I assumed the library would take the default region as I had set it up on the dashboard and I shared another twitter user who assumed and saw the same error. Would be best to make region mandatory and use an enum so people don't see this error.
- Better error message would also be helpful here,

**Comment by doghouch** [comment]
@deepanprabhu Agreed - the documentation for available regions could be better. 

As for default regions -- if none is specified, it uses `DE`/Germany. Warning users would be a bit difficult without hardcoding a list of available locations (I'll add a warning if the API adds a call for listing available regions). 

Thanks for opening the issue, though -- totally missed the tweet :(
