### ISSUE TITLE
downloadObject() error Server returned HTTP response code: 400

### ISSUE THREAD

**Issue by adihanifsdr** [BunnyWay/BunnyCDN.Java.Storage#4]
Hello guys,

I have many files and i successfully download those but i have problem with **only several files** that can't be downloaded because of this error:
`java.lang.Exception: java.io.IOException: Server returned HTTP response code: 400 for URL: https://storage.bunnycdn.com/xxxxxxxx/xxxxxxx/x/x/xxxx.zip`

This problems only happens with this **several files**. what i already tried:

1. Delete then re-upload again
2. Re-upload this file with different name, and then try download it again from my Java app 
3. Checking for file corrupt, no this file isn't corrupt because i can opened it

All of those attempt doesn't seem to make it work.

The URL seems fine, i even try it on the browser and i can access it. Any explanation regarding this error?

**Comment by adihanifsdr** [comment]
Based on this articles [https://support.bunnycdn.com/hc/en-us/articles/360024887131-Typical-HTTP-Response-Codes](url), i know that 400 means Bad Request / The server could not understand the request that it was sent. But why this is happen only to my several files? Re-uploading with different names also doesn't work

**Comment by doghouch** [comment]
Edit #2: @adihanifsdr 

I've repaired the first issue; I think I know why you're experiencing issues with **downloadObject()** -- I'll try to have it fixed by tomorrow.

**Comment by doghouch** [comment]
Just to confirm -- @adihanifsdr:

What was the name of the file?

**Comment by adihanifsdr** [comment]
@doghouch 
1. Belakang Hangar Heli - Copy.BGL
2. Belakang Hangar Heli.BGL
3. Hotel Hakaya - Copy.BGL
4. Hotel Hakaya.BGL

Do you also need the file to test?

**Comment by doghouch** [comment]
@adihanifsdr I don’t need a file right now — I’ll try to replicate the issue with your file name(s).

Thank you for your patience :-)

**Comment by adihanifsdr** [comment]
@doghouch I found something interesting, the downloadObject() seems can't download files that contains title 'space Ha'. I tried on upload file with name `A Ha.txt` and `B Ha.txt` and try to download it on my Java app and it fails.

**Comment by adihanifsdr** [comment]
I found the solution, check out my pull request https://github.com/BunnyWay/BunnyCDN.Java.Storage/pull/5

**Comment by doghouch** [comment]
@adihanifsdr Honestly, I would’ve never thought that spaces needed to replaced by their HEX equiv. (I thought that Java’s HttpsUrlConnection would handle that)

Thanks again — I’ve looked over the changes and it looks good. PR accepted and I’ll close the issue.
