### ISSUE TITLE
Please a thought, remove Jackson dependency from inside lib

### ISSUE THREAD

**Issue by harmeetsingh-work** [BunnyWay/BunnyCDN.Java.Storage#8]
I am getting duplicate class error in my Android project and had to exclude my Jackson library.

I am not a pro but thinking wouldn't it be better to exclude Jackson from inside lib ?

Thankyou, :)

**Comment by doghouch** [comment]
Hello,

Are you using the precompiled JAR?

**Comment by harmeetsingh-work** [comment]
@doghouch yes.

**Comment by doghouch** [comment]
@blackadmin Hello,

I'll make note to include both versions in future updates. For now, I'll attach a JAR file that doesn't bundle Jackson -- you should be able to use this without any problems. Side note: the version bundled uses Jackson 2.9.9.3.

(I'll upload it shortly)

**Comment by doghouch** [comment]
Hello, 

I've published a 1.0.3 with your changes and additional bugfixes. ([JAR w/o Jackson bundled](https://github.com/BunnyWay/BunnyCDN.Java.Storage/releases/download/1.0.3/BCDN-NoDependencies.jar))

Thanks again for your contribution!

**Comment by harmeetsingh-work** [comment]
Tried, Its working great. Thank you.
But jar still contains Jackson jar, dont know if it will affect final app size.

Also now response code is getting returned, GREAT, thank you. :)

**Comment by harmeetsingh-work** [comment]
Don't know but when doing release build for android getting error:
```
Execution failed for task ':app:packageReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'root/lib/jackson-databind-2.9.9.3.jar' uses reserved file or directory name 'lib'.
```

**Comment by doghouch** [comment]
Try this one instead: [BCDNStorage.zip](https://github.com/BunnyWay/BunnyCDN.Java.Storage/files/4991855/BCDNStorage.zip)

I just copied the project over and removed all references to Jackson. You'll need to import them (which I see you've done already) -- that error was pointing to the fact that the dependencies were being stored in an internal folder called "lib." This is no longer being done -- it should work fine now.

**Comment by doghouch** [comment]
Marking as closed since the issue seems to be resolved.
